name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          tools: composer

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Install Laravel dependencies
      - name: Install Laravel dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Install frontend dependencies and build directly into backend/public
      - name: Build frontend with Vite into Laravel public folder
        run: |
          cd frontend
          npm install
          npm run build

      # Configure Laravel environment
      - name: Configure Laravel environment
        run: |
          cd backend
          echo "APP_ENV=production" >> .env
          echo "APP_URL=https://104384876laravel-cwh4axg4d4h5f0ha.southeastasia-01.azurewebsites.net" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "FASTAPI_URL=https://104384876fastapi-brbbdqb0g7b9hrb4.southeastasia-01.azurewebsites.net" >> .env
          echo "DB_SSL_CA=/home/site/wwwroot/storage/certs/DigiCertGlobalRootCA.crt.pem" >> .env

      # Generate Laravel application key
      - name: Generate Laravel application key
        run: |
          cd backend
          php artisan key:generate --force
          echo "APP_KEY=$(php artisan key:generate --show --force)" >> .env

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 104384876laravel
          slot-name: production
          publish-profile: ${{ secrets.AZURE_LARAVEL_PUBLISH_PROFILE }}
          package: ./backend
