name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/fastapi/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        cd backend/fastapi
        pip install -r requirements.txt
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '104384876FastAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_FASTAPI_PUBLISH_PROFILE }}
        package: './backend/fastapi'