name: Deploy FastAPI (Container)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fastapi
      IMAGE_TAG: ${{ github.sha }}
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
    steps:
      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 104384876FastAPIContainer   # EXACT Web App name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_STAGING_APP }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}