name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '!backend/fastapi/**'  # Exclude FastAPI directory
      - '.github/workflows/deploy-laravel.yml'  # Include workflow file itself
  workflow_dispatch:  # Keep manual trigger option


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          tools: composer

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Install Laravel dependencies
      - name: Install Laravel dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Install frontend dependencies and build directly into backend/public
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          ls -l dist/ || { echo "dist/ directory missing"; exit 1; }
          ls -l dist/assets/ || { echo "dist/assets/ directory missing"; exit 1; }
          cat dist/index.html || { echo "dist/index.html missing"; exit 1; }

      - name: Copy frontend build to Laravel public folder
        run: |
          cd backend/public
          mv index.php ../index.php.tmp 2>/dev/null || true
          mv .htaccess ../.htaccess.tmp 2>/dev/null || true
          cd ../..
          rm -rf backend/public/*
          cp -r frontend/dist/. backend/public/ || { echo "Copy failed"; exit 1; }
          mv backend/index.php.tmp backend/public/index.php 2>/dev/null || true
          mv backend/.htaccess.tmp backend/public/.htaccess 2>/dev/null || true
          ls -l backend/public/
          ls -l backend/public/assets/
          cat backend/public/index.html || { echo "index.html missing after copy"; exit 1; }

      # Configure Laravel environment
      - name: Configure Laravel environment
        run: |
          cd backend
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_URL=https://104384876laravel-cwh4axg4d4h5f0ha.southeastasia-01.azurewebsites.net" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "FASTAPI_URL=https://104384876fastapi-brbbdqb0g7b9hrb4.southeastasia-01.azurewebsites.net" >> .env
          echo "DB_SSL_CA=/home/site/wwwroot/storage/certs/DigiCertGlobalRootCA.crt.pem" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env  

      - name: Configure document root
        run: |
          cd backend
          chmod +x startup.sh
          echo "STARTUP_COMMAND=/home/site/wwwroot/startup.sh" >> .env

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 104384876laravel
          slot-name: production
          publish-profile: ${{ secrets.AZURE_LARAVEL_PUBLISH_PROFILE }}
          package: ./backend
